[package]
name = "xvalidate-py"
version = "0.1.0"
description = "Python native runtime bindings for x-validations."
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
rust-version.workspace = true
publish.workspace = true

[lib]
name = "xvalidate"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module"] }
pythonize = "0.28"
serde_json = "1"
xvalidations-core = { path = "../xvalidations-core" }
