name: CI

on: push

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-python@v7
              with:
                  python-version-file: pyproject.toml
            - uses: astral-sh/setup-uv@v10.0.1
              with:
                  enable-cache: true

            - name: Install dependencies
              run: |
                  uv sync --locked --group dev
                  uv pip install pytest-github-actions-annotate-failures

            - name: Lint
              run: uv run prek run --all-files --fail-fast

            - name: Test
              run: uv run pytest
